In [20]:
import pypsa

wind_network = pypsa.Network()
wind_network.set_snapshots(range(4))
wind_network.add("Bus", "electricity")
wind_network.add("Bus", "demand")
wind_network.add(
    "Generator",
    "wind turbine",
    bus="electricity",
    p_nom=100,
    p_max_pu=[0.2, 0.8, 0.4, 0.1],
    marginal_cost=1,
)
wind_network.add("Load", "demand", bus="demand", p_set=[20, 80, 40, 10])
wind_network.add("Link", "transmission line", bus0="electricity", bus1="demand", p_nom=100)

wind_network.optimize(solver_name="highs")
wind_network.generators_t.p.round(2)

/var/folders/c3/657p__892k72qxh6r8fdkqsh0000gn/T/ipykernel_20852/584694927.py:18: FutureWarning: The default value of `include_objective_constant` will change from True to False in version 2.0. Set `include_objective_constant` explicitly to suppress this warning. Using False improves LP numerical conditioning by not including the objective constant as a variable.
  wind_network.optimize(solver_name="highs")
WARNING:pypsa.consistency:The following buses have carriers which are not defined. Run n.sanitize() to add them. Components with undefined carriers:
Index(['electricity', 'demand'], dtype='object', name='name')
WARNING:pypsa.consistency:The following links have carriers which are not defined. Run n.sanitize() to add them. Components with undefined carriers:
Index(['transmission line'], dtype='object', name='name')
INFO:linopy.model: Solve problem using Highs solver
INFO:linopy.io: Writing time: 0.03s
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 8 primals, 24 duals
Objective: 1.50e+02
Solver: highs
Runtime: 0.00s
MIP gap: inf
Dual bound: 0.00e+00
Solver model: available
Solver message: Optimal

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper were not assigned to the network.

Running HiGHS 1.13.1 (git hash: n/a): Copyright (c) 2026 under MIT licence terms
LP linopy-problem-7f0w6vg2 has 24 rows; 8 cols; 28 nonzeros
Coefficient ranges:
  Matrix  [1e+00, 1e+00]
  Cost    [1e+00, 1e+00]
  Bound   [0e+00, 0e+00]
  RHS     [1e+01, 1e+02]
Presolving model
0 rows, 0 cols, 0 nonzeros  0s
0 rows, 0 cols, 0 nonzeros  0s
Presolve reductions: rows 0(-24); columns 0(-8); nonzeros 0(-28) - Reduced to empty
Performed postsolve
Solving the original LP from the solution after postsolve

Model name          : linopy-problem-7f0w6vg2
Model status        : Optimal
Objective value     :  1.5000000000e+02
P-D objective error :  0.0000000000e+00
HiGHS run time      :          0.00

name      wind turbine
snapshot
0                 20.0
1                 80.0
2                 40.0
3                 10.0

In [ ]:

bess = pypsa.Network()
bess.set_snapshots(range(4))
bess.add("Bus", "electricity")
bess.add("Bus", "demand")
bess.add(
    "Generator",
    "solar",
    bus="electricity",
    p_nom=100,
    p_max_pu=[0, 1, 0, 0],
    marginal_cost=0,
)
bess.add("Generator", "grid", bus="electricity", p_nom=100, marginal_cost=50)
bess.add("Load", "demand", bus="demand", p_set=[40, 80, 40, 40])
bess.add(
    "StorageUnit",
    "battery",
    bus="electricity",
    p_nom=30,
    max_hours=2,
    efficiency_store=0.9,
    efficiency_dispatch=0.9,
    cyclic_state_of_charge=True,
    marginal_cost=1,
)
bess.add("Link", "transmission line", bus0="electricity", bus1="demand", p_nom=100)
bess.optimize(solver_name="highs")
bess.storage_units_t.state_of_charge.round(2)

/var/folders/c3/657p__892k72qxh6r8fdkqsh0000gn/T/ipykernel_20852/2403503794.py:29: FutureWarning: The default value of `include_objective_constant` will change from True to False in version 2.0. Set `include_objective_constant` explicitly to suppress this warning. Using False improves LP numerical conditioning by not including the objective constant as a variable.
  bess.optimize(solver_name="highs")
WARNING:pypsa.consistency:The following buses have carriers which are not defined. Run n.sanitize() to add them. Components with undefined carriers:
Index(['electricity', 'demand'], dtype='object', name='name')
WARNING:pypsa.consistency:The following links have carriers which are not defined. Run n.sanitize() to add them. Components with undefined carriers:
Index(['transmission line'], dtype='object', name='name')
INFO:linopy.model: Solve problem using Highs solver
INFO:linopy.io: Writing time: 0.04s
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 24 primals, 60 duals
Objective: 5.21e+03
Solver: highs
Runtime: 0.00s
MIP gap: inf
Dual bound: 0.00e+00
Solver model: available
Solver message: Optimal

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance were not assigned to the network.

Running HiGHS 1.13.1 (git hash: n/a): Copyright (c) 2026 under MIT licence terms
LP linopy-problem-y2kfpnzt has 60 rows; 24 cols; 88 nonzeros
Coefficient ranges:
  Matrix  [9e-01, 1e+00]
  Cost    [1e+00, 5e+01]
  Bound   [0e+00, 0e+00]
  RHS     [3e+01, 1e+02]
Presolving model
5 rows, 14 cols, 20 nonzeros  0s
Dependent equations search running on 5 equations with time limit of 1000.00s
Dependent equations search removed 0 rows and 0 nonzeros in 0.00s (limit = 1000.00s)
5 rows, 14 cols, 20 nonzeros  0s
Presolve reductions: rows 5(-55); columns 14(-10); nonzeros 20(-68)
Solving the presolved LP
Using dual simplex solver
  Iteration        Objective     Infeasibilities num(sum)
          0     0.0000000000e+00 Ph1: 0(0) 0.0s
          6     5.2062000000e+03 Pr: 0(0) 0.0s

Performed postsolve
Solving the original LP from the solution after postsolve

Model name          : linopy-problem-y2kfpnzt
Model status        : Optimal
Simplex   iterations: 6
Objective value     :  5.2062000000e+03
P-D objective error :  0.0000000000e+00
HiGHS run time      :          0.00

name      battery
snapshot
0            -0.0
1            18.0
2            18.0
3            -0.0

In [ ]:

def
fdfsfdffsdfsdffsdfdfsdffdsdfsdfdfsf

/var/folders/c3/657p__892k72qxh6r8fdkqsh0000gn/T/ipykernel_20852/2315651111.py:24: FutureWarning: The default value of `include_objective_constant` will change from True to False in version 2.0. Set `include_objective_constant` explicitly to suppress this warning. Using False improves LP numerical conditioning by not including the objective constant as a variable.
  hydrogen.optimize(solver_name="highs")
WARNING:pypsa.consistency:The following buses have carriers which are not defined. Run n.sanitize() to add them. Components with undefined carriers:
Index(['electricity', 'hydrogen'], dtype='object', name='name')
WARNING:pypsa.consistency:The following links have carriers which are not defined. Run n.sanitize() to add them. Components with undefined carriers:
Index(['electrolyzer'], dtype='object', name='name')
INFO:linopy.model: Solve problem using Highs solver
INFO:linopy.io: Writing time: 0.02s
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 8 primals, 24 duals
Objective: 1.02e+03
Solver: highs
Runtime: 0.00s
MIP gap: inf
Dual bound: 0.00e+00
Solver model: available
Solver message: Optimal

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper were not assigned to the network.

Running HiGHS 1.13.1 (git hash: n/a): Copyright (c) 2026 under MIT licence terms
LP linopy-problem-7oii5gog has 24 rows; 8 cols; 28 nonzeros
Coefficient ranges:
  Matrix  [7e-01, 1e+00]
  Cost    [1e+00, 1e+01]
  Bound   [0e+00, 0e+00]
  RHS     [7e+00, 1e+02]
Presolving model
0 rows, 0 cols, 0 nonzeros  0s
0 rows, 0 cols, 0 nonzeros  0s
Presolve reductions: rows 0(-24); columns 0(-8); nonzeros 0(-28) - Reduced to empty
Performed postsolve
Solving the original LP from the solution after postsolve

Model name          : linopy-problem-7oii5gog
Model status        : Optimal
Objective value     :  1.0200000000e+03
P-D objective error :  0.0000000000e+00
HiGHS run time      :          0.00

name      electricity input  hydrogen output
snapshot
0                      -0.0              0.0
1                      10.0             -7.0
2                      -0.0              0.0
3                      10.0             -7.0